# ansible-playbook play.yml -e "host=bunrning"
# use -e "host=burning" to change from default
---
- name: Install remote facts
  hosts: "{{ host | default('localhost') }}"
  vars: 
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    - name: create remote directory
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
      become: true

    - name: install new facts
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}" 
      become: true
