# File name: install_apache.yml (with yum)
---
- hosts: all
  tasks:
  - name: "Install Apache"
    yum: name={{ item }} state=present
    with_items:
    - httpd

  - name: "Turn on Apache and set it to run on boot"
    service: name={{ item }} state=started enabled=yes
    with_items:
    - httpd 
