# File name: install_apache.yml (with yum)
---
- hosts: all
  tasks:
  - name: "Install Apache"
    yum: pkg={{ item }} state=installed
    with_items:
    - httpd
    notify:
      - Start httpd

  handlers:
  - name: Start httpd
    service: name={{ item }} state=started enabled=yes
    with_items:
    - httpd 
