---
- hosts: "{{ host | default('localhost') }}"
  become: yes
  gather_facts: yes

  tasks: 
    - name: check mariadb status
      raw:  service mariadb status
      ignore_errors: yes # continue running, even if mariadb is not running, because this playbook
                         # is going to act upon the result of this command. It might do something
                         # even if maraidb currently is NOT active
                         # To do This, the result of this command is stored in the result.rc variable
                         # in the next line, and thi result.rc is referred to in the when statement
      register: result   # This saves information about the result int, the result variable
    - debug: var=result

    - name: install http if mariadb is not active
      apt: 
        name: httpd
        state: installed
      register: result2
      when:  result == false and not result|skipped  # this evaluates the output of the check task and will only
                           # restart if the exit code fo the systemctl command is 0 
                           # notice the indentation level of the when statement
    - debug: var=result2

    - name: start httpd
      service: 
        name: httpd
        state: started
      when: result2 == true and not result2|skipped 
