---

# run with ansible-playbook <filename> -k
# (make sure to add the IPs of machine to /etc/ansible/hosts first)

- hosts: lxcall
  gather_facts: Flase
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo 

  tasks:
   - name: Install Python 2
     raw:  test -e /user/bin/python || (apt-get update && apt-get install -y python)

   - name: Fancy way of doing authorized_keys
     authorized_key: user=root
                     exclusive=no
                     key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
