---
- name: scratch pad
  hosts: localhost
  gather_facts: false
  vars:
    api:
      v2: true
    setting: a_val
    feature:
      enabled: false
    another_setting: b_val
  tasks:
    - name: pause with render
      pause:
        prompt: "{{ lookup('template', 'prompt.j2') }}"
    - name: print the api version
      debug: 
        msg: "API =  cinder{{ 'v2' if api.v2 else '' }}"

