# File name univrs.yml
# ansible-playbook univrs.yml -e "host=bunrning"
# use -e "host=burning" to change from default
---
- hosts: "{{ host | default('univrs') }}"
  become: yes
  gather_facts: yes
  vars: 
    is_enabled: false
    variables:
      onekey: 
        one: 1
      twokey:
        two: 2
      threekey:
        three: 3
  tasks:
  - shell: echo "hello devops world"
    when: is_enabled 

  - command: echo "{{ item }}"
    with_items: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    when: item > 11

  - name: loop over envirement facts
    debug: msg={{item.key}}={{item.value}}
    with_dict: "{{ ansible_env }}"   

  - name: loop over files and copy
    copy: src={{ item }} dest=/tmp/new.conf
    with_fileglob: "/tmp/*.conf" 

  - name: add line to file 
    lineinfile:
      path: /tmp/new.conf
      line: 'adding this line to file'

  - name: loop do until 
    shell: echo "hello"
    register: output
    retries: 5
    delay: 5
    until: output.stdout.find('hello') != -1   
