# File name univrs.yml
# ansible-playbook univrs.yml -e "var_host=bunrning"
# use -e "host=burning" to change from default
---
- hosts: "{{ host | default('univrs') }}"
  vars: 
    is_enabled: false
  tasks:
  - shell: echo "hello devops world"
    when: is_enabled 

  - command: echo "{{ item }}"
    with_items: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    when: item > 3
